language: node_js

node_js:
  - 'lts/*'

cache:
  directories:
    - ~/.npm
    - node_modules

notifications:
  email:
    on_success: change
    on_failure: always

script:
  - commitlint-travis
  - npm run lint
  - npm run test

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

sudo: false